from django.urls import path
from .views import *
from logic.views import *

urlpatterns = [
    path('', home, name='home'),
    path('about_us/', about_us, name='about_us'),
    path('login/', user_login, name='login'),
    path('verify_user/',verify_user, name='verify_user'),
    path('gallery/', gallery, name='gallery'),
    path('calendar/', calendar, name='calendar'),
    path('notices/', notices, name='notices'),
    path('results/', results, name='results'),
    path('contact/', contact, name='contact'),
    path('academics/', academics, name='academics'),
    path('faculty',faculty, name='faculty'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', user_logout, name='logout'),
    path('edit_contact/', edit_contact, name='edit_contact'),
    path('edit_academics/', edit_academics, name='edit_academics'),
    path('show_events/', show_events, name='show_events'),
    path('add_event/', add_event, name='add_event'),
    path('edit_event/<int:event_id>/', edit_event, name='edit_event'),
    path('delete_event/<int:event_id>/', delete_event, name='delete_event'),
    path('show_notices/', show_notices, name='show_notices'),
    path('add_notice/', add_notice, name='add_notice'),
    path('edit_notice/<int:notice_id>/', edit_notice, name='edit_notice'),
    path('delete_notice/<int:notice_id>/', delete_notice, name='delete_notice'),
    path('edit_about_us/', edit_about_us, name='edit_about_us'),
    path('edit_school_video/', edit_school_video, name='edit_school_video'),
    path('edit_homepage/',edit_homepage, name='edit_homepage'),
    path('edit_results/', edit_results, name='edit_results'),
    path('edit_SEE_results/', edit_SEE_results, name='edit_SEE_results'),
    path('edit_SEE_toppers/', edit_SEE_toppers, name='edit_SEE_toppers'),
    path('edit_Plus2_results/', edit_Plus2_results, name='edit_Plus2_results'),
    path('edit_Plus2_toppers/', show_streams, name='show_streams'),
    path('edit_Plus2_toppers/<str:stream>/', edit_Plus2_toppers, name='edit_Plus2_toppers'),
    path('edit_faculty/', edit_faculty, name='edit_faculty'),
    path('edit_leaders/', edit_leaders, name='edit_leaders'),
    path('edit_table/', edit_table, name='edit_table'),
    path('show_months/', show_months, name='show_months'),
    path('show_calendar/<int:month_id>', show_calendar, name='show_calendar'),
    path('update_month/', update_month, name='update_month'),
    path('send_email/', send_email, name='send_mail'),
]
